server:
  port: 80
logging:
  config: src/main/resources/config/logback.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qqbot?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update