server:
  port: 8080
logging:
  config: bot-server/src/main/resources/config/logback-spring.xml
spring:
  datasource:
    qqbot:
      jdbcUrl: jdbc:mysql://localhost:5211/qqbot?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 972583048
      driver-class-name: com.mysql.cj.jdbc.Driver
    admin:
      jdbcUrl: jdbc:mysql://localhost:5211/qqbotAdmin?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 972583048
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl