server:
  port: 8080
logging:
  config: bot-api/src/main/resources/config/logback.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qqbot?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 972583048
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl